### ISSUE TITLE
Incognito main info Deploy

### ISSUE THREAD

**Issue by Ljduley12** [Thesecondalthowcool/Incognito-Static-Version#1]
### Deploying 
@Amethystnetwork-dev 
<html>
  <body>
    <h1>Deploying</h1>
    <details>
      <summary>Information?</summary>
      <p>Render - When I deploy, it shows an error.</p>
      <p>What can I deploy this to?</p>
    </details>
  </body>
</html>

**Comment by Thesecondalthowcool** [comment]
wdym

**Comment by Thesecondalthowcool** [comment]
ok on discord
